### ISSUE TITLE
Possible new verb/mechanic: fix

### ISSUE THREAD

**Issue by kberg721** [irtaylor/Capstone_Adventure#11]
Related Issues: #1, #2

If we're hurting for verbs, one mechanic I was thinking of is whether we can fix our items. We could give items a num_uses attribute, and every time we use it we can decrement the number by one. We If we run out of uses, we would always give a failure message.

When we run out of uses: we could have it so you have to return to the garage/workshop to repair your items. We could also maybe have a tool kit item that can have a limited number of repairs available.

thoughts?

**Comment by smcreamer** [comment]
Added verb recharge that takes battery and recharges item if the item is able to be recharged.  Checks for num_uses field in Item object to determine if item can be recharged.  Must return to the garage to recharge an item.
