### ISSUE TITLE
add actions to features

### ISSUE THREAD

**Issue by irtaylor** [irtaylor/Capstone_Adventure#13]
Add an actions attribute in JSON data to the features to allow interactions.
E.g `eat spargeglur`: result: `'You threw up everywhere, Morty.'`

**Comment by smcreamer** [comment]
Implemented in commit [221c9cf](https://github.com/irtaylor/Capstone_Adventure/commit/221c9cfa30a40ea6cff705e1221554ae07d8ed29).
