### ISSUE TITLE
Add "action" verbs to parser.

### ISSUE THREAD

**Issue by kberg721** [irtaylor/Capstone_Adventure#2]
"Your game must support an action vocabulary space (verbs) of at least ten primary actions (hit, pull, go, eat, etc.). These verbs must allow interaction with each feature in each room (a generic "you can't eat that" type of message is OK to use with some verbs)."

We also should decide what action verbs we want to include.

**Comment by smcreamer** [comment]
Current verbs implemented: go, help, inventory, look, drop, take.

Not sure if "look at" is distinct from "look".  They are in the instructors list when he lists them out to explain functionality, but not sure if it applies to the count.

Unsure how aliases fit into this.  It seems like "get" and "use" would be aliased by a lot of things (shoot, port, even take); would be a drag if we made "use" "too" good.
