### ISSUE TITLE
Disposable items aren't removed from inventory when used

### ISSUE THREAD

**Issue by smcreamer** [irtaylor/Capstone_Adventure#21]
When using money to trigger the event in Blips and Chitz's Arcade room, the money is still in inventory after using it.

**Comment by kberg721** [comment]
I think for now we can probably leave it. For story's sake we could say we have more money than a game in the arcade costs. If we get to the point where we have all the other requirements taken care of, we can implement a num_uses attribute that discards an item after we use it enough times.

**Comment by irtaylor** [comment]
easy fix: give the items a "single_use" flag. if that flag is set, then once the item is used, remove it from inventory.

**Comment by kberg721** [comment]
Made it so all items had a num_uses attribute. If the num_uses reaches 0 and it isn't rechargeable (another attribute I added), it gets thrown out.
