### ISSUE TITLE
Implement world travel restrictions

### ISSUE THREAD

**Issue by kberg721** [irtaylor/Capstone_Adventure#7]
A player can only travel to certain worlds based on how many processor chips they have.

**Comment by smcreamer** [comment]
All the Processors are currently being pulled from the same json file; is there a specific way we want to distinguish them or should we restrict travel based on the number in possession of the player (could be a flag attached to the player that increments as more processors are obtained)?

**Comment by kberg721** [comment]
I like the idea of just keeping track of a number variable on the Player object. Although it may get tricky if we need to maintain the "we can drop any item in any room" aspect. Brewster might give us some creative freedom where he will see why we wouldn't want to do that because processor chips are a different class of items than the others, in that we need them to travel.

**Comment by irtaylor** [comment]
i was thinking that combining processor chips and portal gun would "destroy" the chip, and it would no longer be a part of their inventory. this is something we'll need to discuss as far as distinguishing goes.

**Comment by smcreamer** [comment]
That's an interesting idea.  Could also give us another verb.
